# Generated by Django 5.0 on 2024-08-09 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUsers', '0001_initial'),
        ('SubOrganizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subOrganizations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SubOrganizations.suborganization'),
        ),
    ]
