# Generated by Django 5.0 on 2024-05-08 17:01

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUsers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='education',
            field=models.CharField(choices=[('BSc', 'BSc'), ('Ms', 'Ms'), ('PhD', 'PhD'), ('Prof', 'Prof')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
