# Generated by Django 5.0 on 2024-10-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUsers', '0002_initial'),
        ('SubOrganizations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='subOrganizations',
        ),
        migrations.AddField(
            model_name='customuser',
            name='subOrganizations',
            field=models.ManyToManyField(blank=True, null=True, to='SubOrganizations.suborganization'),
        ),
    ]
