# Generated by Django 5.0 on 2024-05-08 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUserPermissions', '0002_rename_is_calculator_customuserpermission_add_manager_and_more'),
        ('CustomUsers', '0002_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CustomUserPermissions.customuserpermission'),
            preserve_default=False,
        ),
    ]
