# Generated by Django 5.0 on 2024-10-18 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUsers', '0004_alter_customuser_suborganizations'),
        ('Projects', '0001_initial'),
        ('SubOrganizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='projects',
            field=models.ManyToManyField(to='Projects.project'),
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='subOrganizations',
        ),
        migrations.AddField(
            model_name='customuser',
            name='subOrganizations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SubOrganizations.suborganization'),
        ),
    ]
