# Generated by Django 5.0 on 2024-10-18 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUsers', '0006_alter_customuser_projects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='admin',
            new_name='admin',
        ),
    ]
