# Generated by Django 5.0 on 2024-05-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('add_subOrganization', models.BooleanField(default=False)),
                ('add_manager', models.BooleanField(default=False)),
                ('add_project', models.BooleanField(default=False)),
                ('user_access', models.BooleanField(default=False)),
            ],
        ),
    ]
