# Generated by Django 5.0 on 2024-05-08 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUserPermissions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuserpermission',
            old_name='is_calculator',
            new_name='add_manager',
        ),
        migrations.RenameField(
            model_name='customuserpermission',
            old_name='is_controller',
            new_name='add_project',
        ),
        migrations.RenameField(
            model_name='customuserpermission',
            old_name='is_supporter',
            new_name='add_subOrganization',
        ),
        migrations.RenameField(
            model_name='customuserpermission',
            old_name='is_viewer',
            new_name='view',
        ),
    ]
