# Generated by Django 5.0 on 2024-05-08 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUserPermissions', '0002_rename_is_calculator_customuserpermission_add_manager_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuserpermission',
            old_name='view',
            new_name='user_access',
        ),
    ]
