# Generated by Django 5.0 on 2024-08-09 16:43

import ProjectFiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectFiles', '0002_alter_projectfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfile',
            name='file',
            field=models.FileField(upload_to='files/', validators=[ProjectFiles.models.validate_file_extension]),
        ),
    ]
